# Generated by Django 4.2.5 on 2024-01-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWindow', '0004_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('activity_view', models.CharField(max_length=255)),
                ('link', models.TextField()),
            ],
        ),
    ]
