# Generated by Django 4.2.5 on 2024-01-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainWindow', '0005_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('activity_view', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
